# Generated by Django 3.1.7 on 2021-03-16 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_auto_20210316_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepayment',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.course'),
        ),
    ]
